[package]
name = "lora-inspector"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inspector = { path = "../inspector" }
candle-core = { workspace = true }
