[package]
name = "lora-inspector-rs"
version = "0.1.0"
edition = "2021"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[lib]
crate-type = ["cdylib"]

[dependencies]
memmap2 = "0.9.0"
safetensors = "0.4.0"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_with = "3.4.0"
console_error_panic_hook = "0.1.7"
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.3.1" }
getrandom = { version = "0.2", features = ["js"] }
web-sys = { version = "0.3.65", features = ["console"] }
regex = "1.10.2"

[dev-dependencies]
insta = { version = "1.34.0", features = ["json"] }
