[package]
name = "lora-inspector-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
memmap2 = "0.9.0"
safetensors = "0.4.0"
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.4"
serde_with = "3.4.0"
console_error_panic_hook = "0.1.7"
