# If we want threading
# [target.wasm32-unknown-unknown]
# rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]
# rustflags = ["-C", "target-feature=+bulk-memory,+mutable-globals"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
