# If we want threading
# [target.wasm32-unknown-unknown]
# rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals"]
# rustflags = ["-C", "target-feature=+bulk-memory,+mutable-globals"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.x86_64-unknown-linux-musl]
linker = "/usr/bin/clang-15"
rustflags = [ "-C", "relocation-model=static", "-C", "link-arg=--ld-path=mold" ]
