import test from "ava";
import { parseSDKey } from "../assets/js/moduleBlocks.js";

const rawKeys = `transformer.single_transformer_blocks.0.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.0.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.0.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.0.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.0.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.0.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.1.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.1.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.1.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.1.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.1.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.1.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.10.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.10.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.10.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.10.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.10.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.10.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.11.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.11.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.11.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.11.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.11.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.11.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.12.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.12.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.12.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.12.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.12.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.12.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.13.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.13.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.13.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.13.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.13.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.13.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.14.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.14.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.14.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.14.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.14.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.14.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.15.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.15.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.15.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.15.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.15.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.15.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.16.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.16.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.16.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.16.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.16.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.16.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.17.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.17.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.17.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.17.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.17.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.17.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.18.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.18.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.18.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.18.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.18.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.18.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.19.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.19.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.19.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.19.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.19.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.19.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.2.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.2.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.2.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.2.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.2.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.2.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.20.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.20.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.20.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.20.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.20.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.20.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.21.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.21.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.21.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.21.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.21.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.21.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.22.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.22.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.22.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.22.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.22.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.22.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.23.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.23.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.23.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.23.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.23.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.23.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.24.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.24.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.24.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.24.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.24.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.24.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.25.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.25.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.25.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.25.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.25.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.25.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.26.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.26.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.26.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.26.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.26.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.26.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.27.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.27.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.27.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.27.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.27.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.27.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.28.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.28.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.28.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.28.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.28.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.28.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.29.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.29.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.29.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.29.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.29.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.29.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.3.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.3.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.3.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.3.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.3.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.3.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.30.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.30.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.30.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.30.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.30.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.30.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.31.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.31.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.31.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.31.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.31.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.31.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.32.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.32.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.32.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.32.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.32.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.32.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.33.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.33.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.33.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.33.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.33.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.33.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.34.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.34.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.34.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.34.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.34.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.34.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.35.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.35.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.35.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.35.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.35.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.35.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.36.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.36.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.36.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.36.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.36.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.36.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.37.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.37.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.37.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.37.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.37.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.37.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.4.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.4.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.4.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.4.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.4.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.4.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.5.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.5.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.5.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.5.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.5.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.5.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.6.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.6.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.6.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.6.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.6.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.6.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.7.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.7.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.7.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.7.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.7.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.7.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.8.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.8.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.8.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.8.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.8.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.8.attn.to_v.lora_B.weight
transformer.single_transformer_blocks.9.attn.to_k.lora_A.weight
transformer.single_transformer_blocks.9.attn.to_k.lora_B.weight
transformer.single_transformer_blocks.9.attn.to_q.lora_A.weight
transformer.single_transformer_blocks.9.attn.to_q.lora_B.weight
transformer.single_transformer_blocks.9.attn.to_v.lora_A.weight
transformer.single_transformer_blocks.9.attn.to_v.lora_B.weight
transformer.transformer_blocks.0.attn.to_k.lora_A.weight
transformer.transformer_blocks.0.attn.to_k.lora_B.weight
transformer.transformer_blocks.0.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.0.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.0.attn.to_q.lora_A.weight
transformer.transformer_blocks.0.attn.to_q.lora_B.weight
transformer.transformer_blocks.0.attn.to_v.lora_A.weight
transformer.transformer_blocks.0.attn.to_v.lora_B.weight
transformer.transformer_blocks.1.attn.to_k.lora_A.weight
transformer.transformer_blocks.1.attn.to_k.lora_B.weight
transformer.transformer_blocks.1.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.1.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.1.attn.to_q.lora_A.weight
transformer.transformer_blocks.1.attn.to_q.lora_B.weight
transformer.transformer_blocks.1.attn.to_v.lora_A.weight
transformer.transformer_blocks.1.attn.to_v.lora_B.weight
transformer.transformer_blocks.10.attn.to_k.lora_A.weight
transformer.transformer_blocks.10.attn.to_k.lora_B.weight
transformer.transformer_blocks.10.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.10.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.10.attn.to_q.lora_A.weight
transformer.transformer_blocks.10.attn.to_q.lora_B.weight
transformer.transformer_blocks.10.attn.to_v.lora_A.weight
transformer.transformer_blocks.10.attn.to_v.lora_B.weight
transformer.transformer_blocks.11.attn.to_k.lora_A.weight
transformer.transformer_blocks.11.attn.to_k.lora_B.weight
transformer.transformer_blocks.11.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.11.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.11.attn.to_q.lora_A.weight
transformer.transformer_blocks.11.attn.to_q.lora_B.weight
transformer.transformer_blocks.11.attn.to_v.lora_A.weight
transformer.transformer_blocks.11.attn.to_v.lora_B.weight
transformer.transformer_blocks.12.attn.to_k.lora_A.weight
transformer.transformer_blocks.12.attn.to_k.lora_B.weight
transformer.transformer_blocks.12.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.12.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.12.attn.to_q.lora_A.weight
transformer.transformer_blocks.12.attn.to_q.lora_B.weight
transformer.transformer_blocks.12.attn.to_v.lora_A.weight
transformer.transformer_blocks.12.attn.to_v.lora_B.weight
transformer.transformer_blocks.13.attn.to_k.lora_A.weight
transformer.transformer_blocks.13.attn.to_k.lora_B.weight
transformer.transformer_blocks.13.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.13.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.13.attn.to_q.lora_A.weight
transformer.transformer_blocks.13.attn.to_q.lora_B.weight
transformer.transformer_blocks.13.attn.to_v.lora_A.weight
transformer.transformer_blocks.13.attn.to_v.lora_B.weight
transformer.transformer_blocks.14.attn.to_k.lora_A.weight
transformer.transformer_blocks.14.attn.to_k.lora_B.weight
transformer.transformer_blocks.14.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.14.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.14.attn.to_q.lora_A.weight
transformer.transformer_blocks.14.attn.to_q.lora_B.weight
transformer.transformer_blocks.14.attn.to_v.lora_A.weight
transformer.transformer_blocks.14.attn.to_v.lora_B.weight
transformer.transformer_blocks.15.attn.to_k.lora_A.weight
transformer.transformer_blocks.15.attn.to_k.lora_B.weight
transformer.transformer_blocks.15.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.15.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.15.attn.to_q.lora_A.weight
transformer.transformer_blocks.15.attn.to_q.lora_B.weight
transformer.transformer_blocks.15.attn.to_v.lora_A.weight
transformer.transformer_blocks.15.attn.to_v.lora_B.weight
transformer.transformer_blocks.16.attn.to_k.lora_A.weight
transformer.transformer_blocks.16.attn.to_k.lora_B.weight
transformer.transformer_blocks.16.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.16.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.16.attn.to_q.lora_A.weight
transformer.transformer_blocks.16.attn.to_q.lora_B.weight
transformer.transformer_blocks.16.attn.to_v.lora_A.weight
transformer.transformer_blocks.16.attn.to_v.lora_B.weight
transformer.transformer_blocks.17.attn.to_k.lora_A.weight
transformer.transformer_blocks.17.attn.to_k.lora_B.weight
transformer.transformer_blocks.17.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.17.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.17.attn.to_q.lora_A.weight
transformer.transformer_blocks.17.attn.to_q.lora_B.weight
transformer.transformer_blocks.17.attn.to_v.lora_A.weight
transformer.transformer_blocks.17.attn.to_v.lora_B.weight
transformer.transformer_blocks.18.attn.to_k.lora_A.weight
transformer.transformer_blocks.18.attn.to_k.lora_B.weight
transformer.transformer_blocks.18.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.18.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.18.attn.to_q.lora_A.weight
transformer.transformer_blocks.18.attn.to_q.lora_B.weight
transformer.transformer_blocks.18.attn.to_v.lora_A.weight
transformer.transformer_blocks.18.attn.to_v.lora_B.weight
transformer.transformer_blocks.2.attn.to_k.lora_A.weight
transformer.transformer_blocks.2.attn.to_k.lora_B.weight
transformer.transformer_blocks.2.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.2.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.2.attn.to_q.lora_A.weight
transformer.transformer_blocks.2.attn.to_q.lora_B.weight
transformer.transformer_blocks.2.attn.to_v.lora_A.weight
transformer.transformer_blocks.2.attn.to_v.lora_B.weight
transformer.transformer_blocks.3.attn.to_k.lora_A.weight
transformer.transformer_blocks.3.attn.to_k.lora_B.weight
transformer.transformer_blocks.3.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.3.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.3.attn.to_q.lora_A.weight
transformer.transformer_blocks.3.attn.to_q.lora_B.weight
transformer.transformer_blocks.3.attn.to_v.lora_A.weight
transformer.transformer_blocks.3.attn.to_v.lora_B.weight
transformer.transformer_blocks.4.attn.to_k.lora_A.weight
transformer.transformer_blocks.4.attn.to_k.lora_B.weight
transformer.transformer_blocks.4.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.4.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.4.attn.to_q.lora_A.weight
transformer.transformer_blocks.4.attn.to_q.lora_B.weight
transformer.transformer_blocks.4.attn.to_v.lora_A.weight
transformer.transformer_blocks.4.attn.to_v.lora_B.weight
transformer.transformer_blocks.5.attn.to_k.lora_A.weight
transformer.transformer_blocks.5.attn.to_k.lora_B.weight
transformer.transformer_blocks.5.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.5.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.5.attn.to_q.lora_A.weight
transformer.transformer_blocks.5.attn.to_q.lora_B.weight
transformer.transformer_blocks.5.attn.to_v.lora_A.weight
transformer.transformer_blocks.5.attn.to_v.lora_B.weight
transformer.transformer_blocks.6.attn.to_k.lora_A.weight
transformer.transformer_blocks.6.attn.to_k.lora_B.weight
transformer.transformer_blocks.6.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.6.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.6.attn.to_q.lora_A.weight
transformer.transformer_blocks.6.attn.to_q.lora_B.weight
transformer.transformer_blocks.6.attn.to_v.lora_A.weight
transformer.transformer_blocks.6.attn.to_v.lora_B.weight
transformer.transformer_blocks.7.attn.to_k.lora_A.weight
transformer.transformer_blocks.7.attn.to_k.lora_B.weight
transformer.transformer_blocks.7.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.7.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.7.attn.to_q.lora_A.weight
transformer.transformer_blocks.7.attn.to_q.lora_B.weight
transformer.transformer_blocks.7.attn.to_v.lora_A.weight
transformer.transformer_blocks.7.attn.to_v.lora_B.weight
transformer.transformer_blocks.8.attn.to_k.lora_A.weight
transformer.transformer_blocks.8.attn.to_k.lora_B.weight
transformer.transformer_blocks.8.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.8.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.8.attn.to_q.lora_A.weight
transformer.transformer_blocks.8.attn.to_q.lora_B.weight
transformer.transformer_blocks.8.attn.to_v.lora_A.weight
transformer.transformer_blocks.8.attn.to_v.lora_B.weight
transformer.transformer_blocks.9.attn.to_k.lora_A.weight
transformer.transformer_blocks.9.attn.to_k.lora_B.weight
transformer.transformer_blocks.9.attn.to_out.0.lora_A.weight
transformer.transformer_blocks.9.attn.to_out.0.lora_B.weight
transformer.transformer_blocks.9.attn.to_q.lora_A.weight
transformer.transformer_blocks.9.attn.to_q.lora_B.weight
transformer.transformer_blocks.9.attn.to_v.lora_A.weight
transformer.transformer_blocks.9.attn.to_v.lora_B.weight`;

test("test keys", async (t) => {
  const keys = rawKeys.split("\n");
  for (const key of keys) {
    if (!key.trim()) continue;  // Skip empty lines
    
    const parsed = parseSDKey(key);
    
    // Test that all required properties exist and have the correct types
    t.truthy(parsed, `Failed to parse key: ${key}`);
    t.is(typeof parsed.name, 'string', `'name' should be a string for key: ${key}`);
    t.is(typeof parsed.blockIdx, 'number', `'blockIdx' should be a number for key: ${key}`);
    t.is(typeof parsed.idx, 'number', `'idx' should be a number for key: ${key}`);
    // t.is(typeof parsed.blockId, 'string', `'blockId' should be a string for key: ${key}`);
    // t.is(typeof parsed.subBlockId, 'string', `'subBlockId' should be a string for key: ${key}`);
    t.is(typeof parsed.type, 'string', `'type' should be a string for key: ${key}`);
    t.is(typeof parsed.blockType, 'string', `'blockType' should be a string for key: ${key}`);
    t.is(typeof parsed.isConv, 'boolean', `'isConv' should be a boolean for key: ${key}`);
    t.is(typeof parsed.isAttention, 'boolean', `'isAttention' should be a boolean for key: ${key}`);
    t.is(typeof parsed.isSampler, 'boolean', `'isSampler' should be a boolean for key: ${key}`);
    t.is(parsed.key, key, `'key' should contain the original key string for key: ${key}`);
    
    // Test that the values are consistent with expectations
    if (parsed.isConv) {
      t.is(parsed.type, 'resnet', `When isConv is true, type should be 'resnet' for key: ${key}`);
    }

    if (parsed.isSampler) {
      t.true(['upscaler', 'downscaler'].includes(parsed.type), 
        `When isSampler is true, type should be 'upscaler' or 'downscaler' for key: ${key}`);
    }
    
    // Test that blockIdx is within the expected range
    t.true(parsed.blockIdx >= -1 && parsed.blockIdx <= 48, 
      `'blockIdx' (${parsed.blockIdx}) should be between 0 and 48 for key: ${key}`);
    
    
  }
});
