name: Playwright Tests
on:
  push:
    branches: [ main, master ]
permissions: read-all
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crates/lora-inspector-wasm
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        # https://woodruffw.github.io/zizmor/audits/#artipacked
        persist-credentials: false

    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
      with:
        node-version: lts/*
    - name: Install rust
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build wasm
      run: 
        wasm-pack build --target web --out-name lora-inspector 
        --release --weak-refs crates/lora-inspector-wasm
      working-directory: ./

    - name: Build wasm SIMD
      run: 
        RUSTFLAGS="-C target-feature=+simd128" wasm-pack build --target web 
        --out-name lora-inspector-simd --release --weak-refs crates/lora-inspector-wasm
      working-directory: ./

    - name: Corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install --immutable
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
